/**
 * Generated by Copilot. List of supported currencies. 
 * 
 * https://www.exchangerate-api.com/docs/supported-currencies
 */
export const Currencies = [
  "USD", // United States Dollar
  "EUR", // Euro
  "JPY", // Japanese Yen
  "GBP", // British Pound Sterling
  "AUD", // Australian Dollar
  "CAD", // Canadian Dollar
  "CHF", // Swiss Franc
  "CNY", // Chinese Yuan
  "SEK", // Swedish Krona
  "NZD", // New Zealand Dollar
  "KRW", // South Korean Won
  "SGD", // Singapore Dollar
  "NOK", // Norwegian Krone
  "MXN", // Mexican Peso
  "INR", // Indian Rupee
  "RUB", // Russian Ruble
  "ZAR", // South African Rand
  "TRY", // Turkish Lira
  "BRL", // Brazilian Real
  "TWD", // New Taiwan Dollar 
  "DKK", // Danish Krone
  "PLN", // Polish Zloty
  "THB", // Thai Baht
  "IDR", // Indonesian Rupiah
  "HUF", // Hungarian Forint
  "CZK", // Czech Republic Koruna
  "ILS", // Israeli New Sheqel
  "CLP", // Chilean Peso
  "PHP", // Philippine Peso
  "AED", // United Arab Emirates Dirham
  "COP", // Colombian Peso
  "SAR", // Saudi Riyal
  "MYR", // Malaysian Ringgit
  "RON", // Romanian Leu
  "PKR", // Pakistani Rupee
  "VND", // Vietnamese Dong
  "NGN", // Nigerian Naira
  "EGP", // Egyptian Pound
  "ARS", // Argentine Peso
  "UAH", // Ukrainian Hryvnia
  "QAR", // Qatari Rial
  "KZT", // Kazakhstani Tenge
  "BDT", // Bangladeshi Taka
  "IRR", // Iranian Rial
  "IQD", // Iraqi Dinar
  "KWD", // Kuwaiti Dinar
  "OMR", // Omani Rial
  "RSD", // Serbian Dinar
  "TND", // Tunisian Dinar
  "BYN", // Belarusian Ruble
  "AZN", // Azerbaijani Manat
  "DZD", // Algerian Dinar
  "LBP", // Lebanese Pound
  "LYD", // Libyan Dinar
  "MAD", // Moroccan Dirham
  "UZS", // Uzbekistan Som
  "AFN", // Afghan Afghani
  "ALL", // Albanian Lek
  "AMD", // Armenian Dram
  "AOA", // Angolan Kwanza
  "AWG", // Aruban Florin
  "BAM", // Bosnia-Herzegovina Convertible Mark
  "BBD", // Barbadian Dollar
  "BGN", // Bulgarian Lev
  "BHD", // Bahraini Dinar
  "BIF", // Burundian Franc
  "BMD", // Bermudian Dollar
  "BND", // Brunei Dollar
  "BOB", // Bolivian Boliviano
  "BSD", // Bahamian Dollar
  "BTN", // Bhutanese Ngultrum
  "BWP", // Botswanan Pula
  "BZD", // Belize Dollar
  "CDF", // Congolese Franc
  "CRC", // Costa Rican Colón
  "CVE", // Cape Verdean Escudo
  "DJF", // Djiboutian Franc
  "DOP", // Dominican Peso
  "ERN", // Eritrean Nakfa
  "ETB", // Ethiopian Birr
  "FJD", // Fijian Dollar
  "FKP", // Falkland Islands Pound
  "GEL", // Georgian Lari
  "GIP", // Gibraltar Pound
  "GMD", // Gambian Dalasi
  "GNF", // Guinean Franc
  "GTQ", // Guatemalan Quetzal
  "GYD", // Guyanaese Dollar
  "HKD", // Hong Kong Dollar
  "HNL", // Honduran Lempira
  "HRK", // Croatian Kuna
  "HTG", // Haitian Gourde
  "JMD", // Jamaican Dollar
  "JOD", // Jordanian Dinar
  "KES", // Kenyan Shilling
  "KGS", // Kyrgystani Som
  "KHR", // Cambodian Riel
  "KID", // Kiribati Dollar
  "KMF", // Comorian Franc
  "KPW", // North Korean Won
  "KYD", // Cayman Islands Dollar
  "LAK", // Laotian Kip
  "LKR", // Sri Lankan Rupee
  "LRD", // Liberian Dollar
  "LSL", // Lesotho Loti
  "MGA", // Malagasy Ariary
  "MKD", // Macedonian Denar
  "MMK", // Myanma Kyat
  "MNT", // Mongolian Tugrik
  "MOP", // Macanese Pataca
  "MRO", // Mauritanian Ouguiya
  "MUR", // Mauritian Rupee
  "MVR", // Maldivian Rufiyaa
  "MWK", // Malawian Kwacha
  "NAD", // Namibian Dollar
  "NIO", // Nicaraguan Córdoba
  "NPR", // Nepalese Rupee
  "PAB", // Panamanian Balboa
  "PGK", // Papua New Guinean Kina
  "PYG", // Paraguayan Guarani
  "RWF", // Rwandan Franc
  "SBD", // Solomon Islands Dollar
  "SCR", // Seychellois Rupee
  "SDG", // Sudanese Pound
  "SHP", // Saint Helena Pound
  "SLL", // Sierra Leonean Leone
  "SOS", // Somali Shilling
  "SRD", // Surinamese Dollar
  "SSP", // South Sudanese Pound
  "STD", // São Tomé and Príncipe Dobra
  "SVC", // Salvadoran Colón
  "SZL", // Swazi Lilangeni
  "TJS", // Tajikistani Somoni
  "TMT", // Turkmenistani Manat
  "TOP", // Tongan Pa'anga
  "TTD", // Trinidad and Tobago Dollar
  "TZS", // Tanzanian Shilling
  "UGX", // Ugandan Shilling
] as const;